const express = require("express");
const routesApp = require("../routes/routes");
const menCategoryRoute = require("../routes/menCategory.router");
const womanCategoryRoute = require("../routes/womanCategory.router");
const { dbConnection } = require("../database/index");
const app = express();
const cors = require("cors");
app.use("/", express.static("public"));
app.use(cors());
app.use(express.json());
app.use("/", routesApp, menCategoryRoute, womanCategoryRoute);
dbConnection();
module.exports = app;
