const express = require("express");
const routesApp = require("../routes/routes");
const { dbConnection } =require("../database/index");
const app = express();
const cors = require("cors");
app.use("/", express.static("public"));
app.use(cors());
app.use(express.json());
app.use("/", routesApp);
dbConnection();
module.exports = app;